### ISSUE TITLE
安装完成后选择是否运行和是否开机启动怎么做？

### ISSUE THREAD

**Issue by haoljp** [wangwenx190/InternetFashionedInstaller#1]
安装完成后选择是否运行和是否开机启动怎么做？https://blog.csdn.net/HarounCloud/article/details/50613590

**Comment by wangwenx190** [comment]
添加几个复选框的事，可以参考许可协议那个是如何创建的。我就是参考你链接中的那篇博客写的这个脚本，那个脚本在安装结束后本身就有几个复选框，你也可以直接把那部分脚本直接复制到我这个脚本中，把复选框显示的文字改改就是了。
我只提供思路，不负责实现具体需求。
