### ISSUE TITLE
卸载不干净

### ISSUE THREAD

**Issue by kingsjl** [wangwenx190/InternetFashionedInstaller#2]
安装和卸载时没有判断程序是否运行，程序打开着也能卸载。

**Comment by wangwenx190** [comment]
这个你要先在你自己的程序中创建Mutex，这样Inno Setup才能检测到。C/C++是用CreateMutex，具体用法是CreateMutex(NULL, FALSE, "MyProgramsMutexName")，其他语言你自己搜吧，很好找。记得改掉脚本中的AppMutex，让AppMutex=MyProgramsMutexName（所有提到的MyProgramsMutexName都改成你自己的Mutex）。如果不是你自己写的程序，没有源码，就没法做到这个了，要用其他比较冷僻的办法，你自己搜吧，我自己没用到过所以也不清楚具体怎么做。
