### ISSUE TITLE
关于Inno Setup的license解读

### ISSUE THREAD

**Issue by leoyong** [wangwenx190/InternetFashionedInstaller#3]
你好，请教一下，使用网上的Inno Setup增强版build出的exe文件可以用于商用吗？

inno的license中写道：
2. All redistributions in binary form must retain all occurrences of the
above copyright notice and web site addresses that are currently in
place (for example, in the About boxes).
...
4. Modified versions in source or binary form must be plainly marked as
such, and must not be misrepresented as being the original software.

这里面的binary是指的我通过修改源码编出来的Compil32.exe或者其他dll文件还是进一步指通过整个IDE（这个IDE可能也被人修改过，比如网上的各种增强版）build出来的安装文件呢？如果我要发布这个安装文件用于商用，那应该怎么做呢?

谢谢~

**Comment by wangwenx190** [comment]
你制作的安装程序，不论是用什么版本的inno打包的，都是可以商用的，无需任何额外操作，但inno编译器自身是不能商用的。它这个license的意思是如果你要发布修改版的inno，要带上它的license，而且不能拿来卖钱，但对于inno构建的任何安装程序，它都没有任何限制。

有任何问题欢迎继续交流。
