### ISSUE TITLE
关于botva2.dll

### ISSUE THREAD

**Issue by leoyong** [wangwenx190/InternetFashionedInstaller#4]
你好，有一个问题一直没搞懂，所谓Inno的插件，实际上就是dll文件吗?inno的dll（或者说delphi的dll）和C++的dll有什么不同吗？可以混用吗？

另外，关于botva2.dll这个文件，在网上很难找到相关的资料，但是好像是一个很常用的关于图形编写的库，请问哪里有关于这个库的说明吗？比如里面有哪些API，分别是什么作用之类的。

再次感谢！！~

**Comment by wangwenx190** [comment]
插件一般都是dll，我目前暂时没见过其他形式。

dll都是可以混用的，跟编写它的语言没关系，但要注意32位和64位不能混用。用起来虽然都一样，但你要知道，语言不一样，dll内部生成的代码也是不一样的，只是不影响别人调用而已。

关于那个botva2.dll，它是一个很好用的界面美化插件，但我一直都没找到它的官网，也确实搜不到相关的教程或者文档，我一直都是通过看别人的脚本来学习这个插件的，确实辛苦。

相同的问题在同一个issue下讨论就行，就算这个issue关了也还是可以继续留言的，不用新开一个。

**Comment by leoyong** [comment]
您好，请教一下 WizardForm 这个类，关于它的说明或者用法有什么比较好的文档或者网页吗?

**Comment by wangwenx190** [comment]
我这么跟你说吧，网上关于inno的教程和文档什么的都很少，讲它内部各种类型和函数的文章更是难找，学习inno主要就靠钻研它自带的帮助文档和别人的脚本。

inno毕竟是个小众软件，网上资料很少的，而那些为数不多的资料也基本都是面向初学者的，很少有深入讲解的。inno的插件更甚，大多数插件作者都没提供教程，我全是靠钻研大神的脚本来学习插件的用法的。
