### ISSUE TITLE
高分辨率下控件或图片显示虚化

### ISSUE THREAD

**Issue by xzzh999** [wangwenx190/InternetFashionedInstaller#6]
如题

**Comment by wangwenx190** [comment]
这个问题我早就注意到了，不是高分辨率下发虚，是高DPI下发虚，如果你设置为100%缩放，控件和图片也不会虚化，但只要DPI超过100%，就一定会发虚，这大概是inno自身的问题，我看大多数inno安装包都会这样。大概不是能用脚本修复的，我也没尝试过。

**Comment by wangwenx190** [comment]
最近我试了试最新版的 Inno Setup ，也就是 5.6.1 ，发现默认控件已经不会虚化了，图片只要分辨率够了也不会虚化，你可以用最新版 Inno 重新编译试试，图片你最好也自己替换一下，我自带的这些图片的分辨率本身也不高，一拉伸很容易虚化。

**Comment by wangwenx190** [comment]
我那些图片都是截图截出来的，因此分辨率都挺低的，演示用没问题，真要投入生产品质还是不行的。
