### ISSUE TITLE
关联应图标

### ISSUE THREAD

**Issue by UBTEDU** [wangwenx190/InternetFashionedInstaller#8]
关联应用图标在win7上显示不出来，win10可以

**Comment by wangwenx190** [comment]
`ChangesAssociations = yes` 别忘了设置。还有，inno 只负责刷新图标，不负责具体的关联操作，所有关联图标的操作都是被打包的应用程序自己完成的，图标出现问题肯定是程序自己出问题了，不是 inno 的问题，跟脚本更没有关系了。你应该查查你那个程序出什么问题了。

**Comment by wangwenx190** [comment]
之前我自己的程序也是这样，关联图标突然看不到了，检查到最后发现是我自己的程序出问题了，跟 inno 完全没关系。说到底 inno 只是个打包软件，不处理任何具体的业务逻辑的。
